config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create]
  
  resources :items, only: [:show] do
    resources :comments, only: [:new, :show, :create, :destroy]
  end

  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :content, presence: true, length: { maximum: 255 }
  validates :title, presence: true
  
  has_many :favorites, dependent: :destroy
  has_many :likes, through: :favorites, source: :user
  
  def checklike?(current_user)
    comment.likes.include?(current_user)
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :comment
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorite(comment)
    favorites.find_or_create_by(comment_id: comment.id)
  end
  
  def unfavorite(comment)
    favorite = favorites.find_by(comment_id: comment.id)
    favorite.destroy if favorite
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper 
  include Pagy::Backend

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def new
    @comment = current_user.comments.build
    @item = Item.find(params[:item_id])
  end

  def show
  end

  def create
    @item = Item.find(params[:item_id])
    @comment = current_user.comments.build(comment_params)
    @comment.item_id = @item.id
    if @comment.save
      flash[:success] = 'コメントを投稿しました。'
      redirect_to item_path(@item)
    else
      @comments = current_user.comments.order(id: :desc)
      flash.now[:danger] = 'コメントの投稿に失敗しました。'
      render 'comments/new'
    end
  end

  def destroy
    @comment.destroy
    flash[:success] = 'コメントを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:user_id, :item_id, :title, :content)
  end

  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    comment = Comment.find(params[:comment_id])
    current_user.favorite(comment)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    comment = Comment.find(params[:comment_id])
    current_user.unfavorite(comment)
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
 before_action :require_user_logged_in
  
  def show
    @item = Item.find(params[:id])
    @pagy, @comments = pagy(@item.comments.order(created_at: :desc), items: 3)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.order(id: :desc)
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/comments/_comments.html.erb
<% if comments.any? %>
  <% comments.each do |comment| %>
    <div class="border rounded mb-2">
      <div class="comment fw-bold pt-3">
        <p><%= comment.title %></p>
      </div>
      <div class="comment">
        <p><%=safe_join(comment.content.split("\n"),tag(:br))%></p>
      </div>
      <div class="row commenter" style="padding-left: 15px;">
        <div class="col-6">
        <%= link_to comment.user.name, user_path(comment.user.id), class: "text-decoration-none" %>さん
        </div>
        <div class="col-6 d-flex justify-content-end" pr-3>
          <%= render "favorites/like_button", comment: comment %>
        </div>
      </div>
    </div>
  <% end %>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %> 

app/views/comments/new.html.erb
<div class="container forms border rounded pb-5">
  <div class="text-center my-5">
    <h3><%= @item.name %></h3>
  </div>
  <div class="row-form">
    <div class="col-sm-8 offset-sm-2">
      <%= form_with(model: @comment, url: item_comments_path) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="mb-4">
        <p><%= f.label :title, 'タイトル' %></p>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="mb-4">
        <p><%= f.label :content, 'コメント' %></p>
        <%= f.text_area :content, class: 'form-control', rows: 4 %>
      </div>
      <div class="d-flex justify-content-center py-2">
        <%= f.submit '投稿する', class: 'btn btn-success w-50' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/favorites/_like_button.html.erb
<% if comment.likes.include?(current_user) %>
    <%= form_with(model: current_user.favorites.find_by(comment_id: comment.id), method: :delete) do |f| %>
      <%= hidden_field_tag :comment_id, comment.id %>
      <h6 class="badge rounded-pill good mr-0">
        <%= f.submit 'いいね', class: 'btn btn-sm g' %><span class="gs"><%= comment.likes.count %></span>
      </h6>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.favorites.build) do |f| %>
      <%= hidden_field_tag :comment_id, comment.id %>
      <h6 class="badge rounded-pill no-good">
        <%= f.submit 'いいね', class: 'btn btn-sm ng' %><span class="gs"><%= comment.likes.count %></span>
      </h6>
    <% end %>
  <% end %>

app/views/items/show.html.erb
<div class="container mt-5 px-0 mx-0">
  <div class="row mb-3">
    <h5 class="card-title pr-3"><%= @item.name %></h5>
    <aside class="col-sm-4">
      <div class="card border border-0">
        <div class="card-body p-3">
         <%= image_tag @item.image_name, alt: @item.name, class: "card-img-top" %>
        </div>
      </div>
    </aside>
    <div class="col-sm-8 pt-4">
      <%= @item.content %>
    </div>
  </div>  
  <div class="text-center my-4">
    <%= link_to 'コメントする', new_item_comment_path(@item.id), class: 'btn btn-success' %>
  </div>
  <div class="comments">
    <%= render 'comments/comments', comments: @comments %>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-white mt-5">
    <div class="container"  style="width: 900px;">
      <a class="navbar-brand text-secondary" href="/"><h3>NO CAT, NO LIFE</h3></a>
      
        <div class="navbar justify-content-end">
        <% if logged_in? %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'マイページ', user_path(current_user), class: 'nav-link text-secondary' %></li>
            <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link text-secondary' %></li>
          </ul>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to '会員登録', signup_path, class: 'nav-link text-secondary' %></li>
            <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link text-secondary' %></li>
          </ul>
        <% end %>
      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatLife</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <div class="message">
        <%= render 'layouts/flash_messages' %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<div class="container px-0 mx-0">

  <div class="text-center text-black m-6">
      <p>猫好きなみなさんの</p>
      <p>"I ♥ CAT"な想いを聞かせてください。</p>
  </div>

  
    <div class="row">
      
      <div class="cards col p-0 border border-0">  
         <a href="/items/2"><img class="card-img-top" alt="スコティッシュフォールド" src="/assets/001_s.jpg" /></a>
        <div class="card-body">
          <p class="card-text">スコティッシュフォールド</p>
        </div>
      </div>
      
      <div class="cards col p-0 border border-0">
        <a href="/items/3"><img class="card-img-top" alt="マンチカン" src="/assets/002_s.jpg" /></a>
        <div class="card-body">
          <p class="card-text">マンチカン</p>
        </div>
      </div>
      
      <div class="cards col p-0 border border-0">
        <a href="/items/4"><img class="card-img-top" alt="ロシアンブルー" src="/assets/003_s.jpg" /></a>
        <div class="card-body">
          <p class="card-text">ロシアンブルー</p>
        </div>
      </div>
     
      <div class="cards col p-0 border border-0">
        <a href="/items/5"><img class="card-img-top" alt="アメリカンショートヘア" src="/assets/004_s.jpg" /></a>
        <div class="card-body">
          <p class="card-text">アメリカン<br>ショートヘア</p>
        </div>
      </div>
      
      <div class="cards col p-0 border border-0">
        <a href="/items/6"><img class="card-img-top" alt="ベンガル" src="/assets/005_s.jpg" /></a>
        <div class="card-body">
          <p class="card-text">ベンガル</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="cards col p-0 border border-0">
        <a href="/items/7"><img class="card-img-top" alt="ノルウェージャンフォレストキャット" src="/assets/006_s.jpg" /></a>
        <div class="card-body">
          <p class="card-text">ノルウェージャンフォレストキャット</p>
        </div>
      </div>
      
      <div class="cards col p-0 border border-0">
        <a href="/items/8"><img class="card-img-top" alt="ブリティッシュショートヘア" src="/assets/007_s.jpg" /></a>
        <div class="card-body">
          <p class="card-text">ブリティッシュショートヘアー</p>
        </div>
      </div>
      
      <div class="cards col p-0 border border-0">
       <a href="/items/9"><img class="card-img-top" alt="エキゾチックショートヘア" src="/assets/008_s.jpg" /></a>
        <div class="card-body">
          <p class="card-text">エキゾチック<br>ショートヘアー</p>
        </div>
      </div>
     
      <div class="cards col p-0 border border-0">
        <a href="/items/10"><img class="card-img-top" alt="ラグドール" src="/assets/009_s.jpg" /></a>
        <div class="card-body">
          <p class="card-text">ラグドール</p>
        </div>
      </div>
      
      <div class="cards col p-0 border border-0">
        <a href="/items/11"><img class="card-img-top" alt="メインクーン" src="/assets/010_s.jpg" /></a>
        <div class="card-body">
          <p class="card-text">メインクーン</p>
        </div>
      </div>
    </div>  

</div>

app/views/users/new.html.erb
<div class="container forms border rounded pb-5">
  <div class="text-center my-5">
    <h3>新規会員登録</h3>
  </div>

<div class="row-form">
  <div class="col-sm-8 offset-sm-2">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="mb-4">
        <p><%= f.label :name, 'お名前' %></p>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-4">
        <p><%= f.label :email, 'メールアドレス' %></p>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-4">
        <p><%= f.label :password, 'パスワード' %></p>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-4">
        <p><%= f.label :password_confirmation, 'パスワード(確認用)' %></p>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <div class="d-flex justify-content-center py-2">
        <%= f.submit '登録する', class: 'btn btn-success w-50' %>
      </div>
    <% end %>
      <div class="d-flex justify-content-center py-2">
        <p></p><%= link_to 'すでに会員の方はこちら', login_path %></p>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5 px-0 mx-0">
  <div class="neco-commenter pb-4">
    <h5><%= @user.name %>さんのコメント</h5>
  </div>

  <% @comments.each do |comment| %>
    <div class="row mb-3">
      <h5 class="card-title mt-3"><%= comment.item.name %></h5>
      <aside class="col-sm-4">
        <div class="card border border-0">
          <div class="card-body p-3">
            <%= image_tag  comment.item.image_name, alt: comment.item.name, class: "card-img-top" %>
          </div>
        </div>
      </aside>
      <div class="col-sm-8 pt-4">
        <%= comment.item.content %>
      </div>
    </div> 
        
    <% if current_user == comment.user %>
      <div class="border rounded mb-2">
        <div class="comment fw-bold pt-3">
          <p><%= comment.title %></p>
        </div>
        <div class="comment">
          <%=safe_join(comment.content.split("\n"),tag(:br))%>
        </div>
            
        <div class="delete d-flex justify-content-end pb-2">
          <%= link_to "削除する",item_comment_path(comment.item.id, comment.id), method: :delete, data: { confirm: "本当に削除してよろしいですか？" }, class: 'btn btn-danger' %>
        </div> 
      </div>
      <% else %>
      <div class="border rounded mb-2">
        <div class="comment fw-bold pt-3">
          <p><%= comment.title %></p>
        </div>
        <div class="comment">
          <p><%= comment.content %></p>
        </div>
        <div class="user-favo d-flex justify-content-end">
          <%= render "favorites/like_button", comment: comment %>
        </div>
      </div>      
    <% end %>
  <% end %>
</div>